name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '10'
      
    - name: Install dependencies
      run: npm ci

    - name: Run lint
      run: npm run lint
    
    - name: Run test
      run: npm run test
    
    - name: Run build
      run: npm run build

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ${{ github.workspace }}/coverage/lcov.info
